#!/bin/sh

cd /tmp && \
  wget https://github.com/c-bata/kube-prompt/releases/download/v1.0.0/kube-prompt_v1.0.0_darwin_amd64.zip && \
  unzip kube-prompt_v1.0.0_darwin_amd64.zip && \
  mv kube-prompt /usr/local/bin/
